### ISSUE TITLE
VoteReward 3.0

### ISSUE THREAD

**Issue by LDX-MCPE** [LDX-MCPE/VoteReward#8]
**To-do:**

- [x] Update plugin.yml with new information.
- [x] Update QueryTask.php to use new Request object system.
- [x] Create new Request object class,
- [x] Update Main.php to use new Request object system.
- [x] Update Main.php to pool voting items.
- [x] Implement new server list configuration system.
- [x] Create specifications for server lists to create their VRC files.
- [x] Create specifications for server lists to create their APIs.
- [x] Update global configuration file with new features.
- [x] Debug.

**Comment by addhyangupta** [comment]
What is the API KEY. I am a new guy so I need your help, I really appreciate your awesome plugin but I need help in the API KEY part
